name: Example container build

env:
  DOCKERFILE_DIRECTORY: examples/mycontainer
  IMAGE_NAME: mycontainer

on:
  push:
    branches:
      - main
    paths:
      - 'examples/mycontainer/**'

# To prevent multiple clashing builds
concurrency: mycontainer-post-merge

jobs:
  
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment: test

    steps:
      # Checkout the code to build from
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
        with:
          fetch-depth: '0'

      - name: Build docker image
        run: |
          cd ${GITHUB_WORKSPACE}/${DOCKERFILE_DIRECTORY}
          docker build -t katstevens/${IMAGE_NAME} .
          
      # We can then push the artefact to DockerHub or ECR
